language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8
      env: MCALF_DEPLOY=1
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
install:
  - pip3 install --upgrade pip
  - pip3 install -e .
script: python3 -m pytest || python -m pytest
after_script: cd ~
