variables:
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: ConorMacBride
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - 'v*'

stages:
  - stage: Setup
    jobs:
    - job: check_skip_ci
      steps:
      - checkout: self
      - task: Bash@3
        name: process_commit_message
        inputs:
          targetType: 'inline'
          script: |
            echo "Commit being tested: \"$MERGE_MSG\""
            COMMIT_HASH=$(echo $MERGE_MSG | awk '{print $2}')
            echo "Hash of commit being tested: \"$COMMIT_HASH\""
            MSG=$(git log --format=%B -n 1 $COMMIT_HASH | head -1)
            echo "Message being searched for skip commands: \"$MSG\""
            SET_TRUE="##vso[task.setvariable variable=skipsecond;isOutput=true]true"
            SET_FALSE="##vso[task.setvariable variable=skipsecond;isOutput=true]false"
            if [[ $MSG != *"[skip ci]"* ]]; then echo $SET_FALSE; else echo $SET_TRUE; fi
        env:
          MERGE_MSG: $(Build.SourceVersionMessage)

  - stage: StageOneTests
    displayName: Basic Tests
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        coverage: codecov
        posargs: -n=4

        envs:
        - linux: py39

  - stage: StageTwoTests
    displayName: Detailed Tests
    condition: or(and(succeeded(), eq(dependencies.Setup.outputs['check_skip_ci.process_commit_message.skipsecond'], 'false')), eq(variables['Build.Reason'], 'Manual'))
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        coverage: codecov
        posargs: -n=4

        libraries:
          apt:
            - pandoc

        envs:

        - linux: py37
          libraries: {}
        - linux: py38
          libraries: {}

        - macos: py39
          libraries: {}

        - windows: py39
          libraries: {}

        # Test that the oldest dependency versions with on the latest supported Python version
        - linux: py37-oldestdeps
          libraries: {}

#        - linux: build_docs
#          posargs: " "
#          pytest: false

  - stage: FigureTests
    displayName: Figure Tests
    condition: or(and(succeeded(), eq(dependencies.Setup.outputs['check_skip_ci.process_commit_message.skipsecond'], 'false')), eq(variables['Build.Reason'], 'Manual'))
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        coverage: codecov
        posargs: -n=4
        envs:
        - linux: py39-figure
        - macos: py39-figure
        - windows: py39-figure

  # RELEASING A VERSION: Run more detailed tests if releasing a version (or if triggered manually)
  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['Build.Reason'], 'Manual')) }}:
    - stage: PreReleaseTests
      displayName: Pre-release Tests
      condition: or(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      jobs:
      - template: run-tox-env.yml@OpenAstronomy
        parameters:
          default_python: '3.9'
          coverage: codecov
          posargs: -n=4

          envs:

#          - linux: py37
#          - linux: py38
#          - linux: py39

          - macos: py37
          - macos: py38
#          - macos: py39

          - windows: py37
          - windows: py38
#          - windows: py39

#          - linux: py37-oldestdeps
          - macos: py37-oldestdeps
          - windows: py37-oldestdeps

  # Don't build sdist and wheels for PRs
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - stage: Release
      condition: or(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      jobs:
      - template: publish.yml@OpenAstronomy
        parameters:
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
            pypi_connection_name: 'pypi_endpoint'
            pypi_endpoint_name: 'mcalf'
          libraries:
          - libfftw3-dev
          test_extras: "tests"
          test_command: pytest --pyargs mcalf
          targets:
          - sdist
          - wheels_cp3[7-9]-macosx_x86_64
          - wheels_cp3[7-9]-manylinux*
          - wheels_cp3[7-9]-win_amd64
