variables:
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_MANYLINUX_I686_IMAGE: manylinux2014

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: ConorMacBride
    name: OpenAstronomy/azure-pipelines-templates

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - 'v*'

stages:
  - stage: StageOneTests
    displayName: Basic Tests
    jobs:
    - template: check-skip.yml@OpenAstronomy
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        coverage: codecov
        posargs: -n=4
        envs:
        - linux: py39

  - stage: StageTwoTests
    displayName: Detailed Tests
    condition: or(and(succeeded(), ne(dependencies.StageOneTests.outputs['check_skip.search.found'], 'true')), eq(variables['Build.Reason'], 'Manual'))
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        coverage: codecov
        posargs: -n=4
        envs:
        - linux: py37
        - linux: py38
        - macos: py39
        - windows: py39
        - linux: py37-oldestdeps

  - stage: FigureTests
    displayName: Figure Tests
    condition: or(and(succeeded(), ne(dependencies.StageOneTests.outputs['check_skip.search.found'], 'true')), eq(variables['Build.Reason'], 'Manual'))
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.9'
        coverage: codecov
        posargs: -n=4
        envs:
        - linux: py39-figure
        - macos: py39-figure
        - windows: py39-figure

  # RELEASING A VERSION: Run more detailed tests if releasing a version (or if triggered manually)
  - ${{ if or(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), eq(variables['Build.Reason'], 'Manual')) }}:
    - stage: PreReleaseTests
      displayName: Pre-release Tests
      condition: or(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      jobs:
      - template: run-tox-env.yml@OpenAstronomy
        parameters:
          default_python: '3.9'
          coverage: codecov
          posargs: -n=4
          envs:
          - macos: py37
          - macos: py38
          - windows: py37
          - windows: py38
          - macos: py37-oldestdeps
          - windows: py37-oldestdeps

  # Don't build sdist and wheels for PRs
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - stage: Release
      condition: or(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      jobs:
      - template: publish.yml@OpenAstronomy
        parameters:
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
            pypi_connection_name: 'pypi_endpoint'
            pypi_endpoint_name: 'mcalf'
          libraries:
          - libfftw3-dev
          test_extras: "tests"
          test_command: pytest --pyargs mcalf
          targets:
          - sdist
          - wheels_cp3[7-9]-macosx_x86_64
          - wheels_cp3[7-9]-manylinux*
          - wheels_cp3[7-9]-win_amd64
